### ISSUE TITLE
Explanation on motivation for this project and what it does

### ISSUE THREAD

**Issue by jharris4** [tborges/google-amp-template#1]
Hi, when visiting the github page for this project it's not immediately clear to me what I can use it for and why it exists.

It might be useful if you show an example of how/why you built this project

**Comment by tborges** [comment]
Hey @jharris4 , 
Thanks for visiting my project. I took your advice and enhanced the `README.md` file.    My package right now is very simple, it just copy one file the index.html and paste/clone into another folder.  I'm planning to create a `global` command that works in any folder/subdirectory of my computer.   Example, this package [`svgo` ](https://www.npmjs.com/package/svgo), is installed global and works in any folder/subdirectory.  Have you done anything like that? 

Sorry for opening that "issue" with your package. Do you want me to delete all my Comments about the "issue" that I left?  Let me know anything. 

Thanks

**Comment by jharris4** [comment]
No need to delete your issue or comments. That's what they're for, learning and asking questions!

Nice work on updating the `README.md`, it's much clearer to understand now!

I haven't done something quite like this before, but I think many people refer to this type of project as [boilerplate](https://en.wikipedia.org/wiki/Boilerplate_code).

**Comment by tborges** [comment]
@jharris4 , thank you!  I will read more about it. 

Thanks a lot
